# Generated by Django 4.2 on 2023-04-27 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='account_avatar/')),
                ('position', models.IntegerField(choices=[(0, 'Employer'), (0, 'Worker')])),
                ('location', models.CharField(max_length=221)),
                ('bio', models.TextField()),
                ('company', models.CharField(max_length=221)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
