# Generated by Django 4.2 on 2023-05-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'HR'), (1, 'Candidate'), (2, 'Staff')], null=True),
        ),
    ]
