# Generated by Django 4.2 on 2023-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.IntegerField(choices=[(0, 'HR'), (1, 'Canditate')]),
        ),
    ]
