# Generated by Django 4.2 on 2023-04-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
        migrations.RemoveField(
            model_name='account',
            name='location',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('contry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.contry')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.city'),
            preserve_default=False,
        ),
    ]
