# Generated by Django 4.2 on 2023-04-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_active_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='types',
        ),
        migrations.AddField(
            model_name='job',
            name='types',
            field=models.ManyToManyField(to='job.type'),
        ),
    ]
