# Generated by Django 4.2 on 2023-05-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.position'),
        ),
    ]
