# Generated by Django 4.2 on 2023-05-06 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
    ]
